/* =============================================================================
 * board.c — DynaWatch V4 board hardware initialisation
 * =============================================================================
 */

#include "board.h"
#include "fsl_debug_console.h"

/* ─── BOARD_InitHardware ────────────────────────────────────────────────────
 * Called from app_main.c before any FreeRTOS tasks are created.
 * Order matters: clocks → pins → peripherals → console.
 * -------------------------------------------------------------------------- */
void BOARD_InitHardware(void)
{
    BOARD_InitBootClocks();     /* clock_config.c — generated by MCUXpresso Config Tools */
    BOARD_InitBootPins();       /* pin_mux.c      — generated by MCUXpresso Config Tools */
    BOARD_InitDebugConsole();
}

/* ─── BOARD_InitDebugConsole ────────────────────────────────────────────────
 * Attaches SDK debug console (DbgConsole_Init) to LPUART1 @ 115200.
 * -------------------------------------------------------------------------- */
void BOARD_InitDebugConsole(void)
{
    uint32_t uartClkSrcFreq = BOARD_DEBUG_UART_CLK_FREQ;
    DbgConsole_Init(1U,                         /* instance (LPUART1) */
                    BOARD_DEBUG_UART_BAUDRATE,
                    kSerialPort_Uart,
                    uartClkSrcFreq);
}
